# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_bayer2rgb_0_0/system_bayer2rgb_0_0.xci
# IP: The module: 'system_bayer2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: d:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: d:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_bayer2rgb_0_0/system_bayer2rgb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_bayer2rgb_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_bayer2rgb_0_0/system_bayer2rgb_0_0.xci
# IP: The module: 'system_bayer2rgb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# XDC: d:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc

# XDC: d:/xilinx/project/spartan_cam/spartan_cam.srcs/sources_1/bd/system/ip/system_bayer2rgb_0_0/system_bayer2rgb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_bayer2rgb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
